eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/restaurantdb
#    password: "@Thanhnguyen14#"
#    username: root

spring:
  datasource:
    #db name: userdb
    url: jdbc:mysql://idr-mysql-db.cdsmu4qw4veh.eu-west-2.rds.amazonaws.com:3306/userdb
    username: admin
    password: "password"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # if there is update on data, it will update existing tables, not to create a new one
      ddl-auto: update
    show-sql: true
    #    Convert based language to my SQL based query
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect